import { ThemeColors } from '../types';

export const THEMES: Record<string, ThemeColors> = {
  classic: {
    name: 'Classic Light',
    type: 'classic',
    bodyBg: 'bg-gradient-to-tr from-slate-50 to-slate-100 text-slate-900',
    headerBg: 'bg-slate-900',
    headerBorder: 'border-slate-800',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-500',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200/60',
    btnPrimary: 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-sm cursor-pointer',
    btnSecondary: 'bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border-indigo-100 border cursor-pointer',
    btnAccentBg: 'bg-indigo-600',
    activeText: 'text-indigo-600',
    boardBg: 'bg-white border-slate-200',
    boardGridColor: 'border-slate-200',
    boardSubgridBorder: 'border-slate-400',
    cellBg: 'bg-white hover:bg-slate-100',
    cellGiven: 'text-slate-900 font-bold',
    cellUser: 'text-indigo-600 font-medium',
    cellSelected: 'bg-indigo-100 text-indigo-950 font-semibold',
    cellRelated: 'bg-slate-50/80 text-slate-800',
    cellSameValue: 'bg-violet-100 font-semibold text-violet-900',
    cellError: 'bg-rose-100 text-rose-700',
    keypadBtn: 'bg-white hover:bg-slate-50 text-slate-800 border-slate-200/80 cursor-pointer',
  },
  cosmic: {
    name: 'Cosmic Dark',
    type: 'cosmic',
    bodyBg: 'bg-slate-950 text-slate-100',
    headerBg: 'bg-slate-900/60 backdrop-blur-md',
    headerBorder: 'border-slate-800',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-400',
    cardBg: 'bg-slate-900/60 backdrop-blur-sm border border-slate-800',
    cardBorder: 'border-slate-800/80',
    btnPrimary: 'bg-violet-600 hover:bg-violet-500 text-white shadow-sm cursor-pointer',
    btnSecondary: 'bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 cursor-pointer',
    btnAccentBg: 'bg-violet-600',
    activeText: 'text-violet-400',
    boardBg: 'bg-slate-950 border-slate-800',
    boardGridColor: 'border-slate-800',
    boardSubgridBorder: 'border-indigo-500/80',
    cellBg: 'bg-slate-900 hover:bg-slate-800/75',
    cellGiven: 'text-blue-400 font-bold',
    cellUser: 'text-violet-300 font-medium',
    cellSelected: 'bg-violet-900/60 text-violet-100 font-semibold',
    cellRelated: 'bg-slate-800/40 text-slate-300',
    cellSameValue: 'bg-indigo-950/70 font-semibold text-indigo-200',
    cellError: 'bg-rose-950/60 text-rose-300',
    keypadBtn: 'bg-slate-900 hover:bg-slate-800/80 text-slate-200 border-slate-800 cursor-pointer',
  },
  retro: {
    name: 'Retro Terminal',
    type: 'retro',
    bodyBg: 'bg-black text-green-500 font-mono-tech',
    headerBg: 'bg-zinc-950 border-b border-green-900/50',
    headerBorder: 'border-green-950',
    textPrimary: 'text-green-500',
    textSecondary: 'text-green-600',
    cardBg: 'bg-black border border-green-900/80',
    cardBorder: 'border-green-900/60',
    btnPrimary: 'bg-green-950/60 hover:bg-green-900/80 border border-green-500/80 text-green-400 shadow-sm cursor-pointer',
    btnSecondary: 'bg-zinc-950 hover:bg-zinc-900 border border-green-900/60 text-green-500 cursor-pointer',
    btnAccentBg: 'bg-green-600',
    activeText: 'text-green-400',
    boardBg: 'bg-black border-green-900',
    boardGridColor: 'border-green-950',
    boardSubgridBorder: 'border-green-500',
    cellBg: 'bg-black hover:bg-green-950/30',
    cellGiven: 'text-green-600 font-bold font-mono-tech opacity-80',
    cellUser: 'text-green-400 font-bold font-mono-tech border border-transparent',
    cellSelected: 'bg-green-950 text-green-200 outline outline-2 outline-green-500/50 z-10',
    cellRelated: 'bg-green-950/20 text-green-700',
    cellSameValue: 'bg-green-900/40 text-green-300',
    cellError: 'bg-red-950 text-red-400 border border-red-500',
    keypadBtn: 'bg-black hover:bg-zinc-950 text-green-500 border border-green-900/50 cursor-pointer font-mono-tech',
  },
  sand: {
    name: 'Warm Sand',
    type: 'sand',
    bodyBg: 'bg-[#faf6f0] text-stone-900',
    headerBg: 'bg-stone-900',
    headerBorder: 'border-stone-800',
    textPrimary: 'text-stone-800',
    textSecondary: 'text-stone-500',
    cardBg: 'bg-[#fcfaf7]',
    cardBorder: 'border-stone-200/60',
    btnPrimary: 'bg-amber-800 hover:bg-amber-700 text-white shadow-sm cursor-pointer',
    btnSecondary: 'bg-amber-50 hover:bg-amber-100 text-amber-900 border border-amber-200/60 cursor-pointer',
    btnAccentBg: 'bg-amber-800',
    activeText: 'text-amber-800',
    boardBg: 'bg-[#fcfaf7] border-stone-200',
    boardGridColor: 'border-stone-200',
    boardSubgridBorder: 'border-[#b59d80]',
    cellBg: 'bg-white hover:bg-stone-50',
    cellGiven: 'text-stone-900 font-semibold',
    cellUser: 'text-amber-800 font-bold',
    cellSelected: 'bg-amber-100 text-amber-950 font-semibold',
    cellRelated: 'bg-amber-50/30 text-stone-600',
    cellSameValue: 'bg-amber-100/60 text-amber-900',
    cellError: 'bg-red-100 text-red-700',
    keypadBtn: 'bg-[#fcfaf7] hover:bg-stone-50 text-stone-800 border border-stone-200 cursor-pointer',
  },
  sakura: {
    name: 'Sakura Blossom',
    type: 'sakura',
    bodyBg: 'bg-gradient-to-tr from-rose-50 to-rose-100/40 text-emerald-950',
    headerBg: 'bg-rose-950',
    headerBorder: 'border-rose-900',
    textPrimary: 'text-rose-950',
    textSecondary: 'text-rose-500',
    cardBg: 'bg-white/80 border border-rose-100/60',
    cardBorder: 'border-rose-100',
    btnPrimary: 'bg-rose-500 hover:bg-rose-400 text-white shadow-sm cursor-pointer',
    btnSecondary: 'bg-rose-50 hover:bg-rose-100 text-rose-600 border border-rose-100/60 cursor-pointer',
    btnAccentBg: 'bg-rose-500',
    activeText: 'text-rose-500',
    boardBg: 'bg-white border-rose-200',
    boardGridColor: 'border-rose-150',
    boardSubgridBorder: 'border-rose-450',
    cellBg: 'bg-white hover:bg-rose-50/20',
    cellGiven: 'text-rose-900 font-bold',
    cellUser: 'text-emerald-700 font-semibold',
    cellSelected: 'bg-rose-100 text-rose-950 font-bold',
    cellRelated: 'bg-rose-50/40 text-rose-800',
    cellSameValue: 'bg-rose-100/50 font-semibold text-rose-900',
    cellError: 'bg-red-50 text-red-600 font-semibold border border-rose-200',
    keypadBtn: 'bg-white hover:bg-rose-50/40 text-rose-800 border border-rose-100/60 cursor-pointer',
  },
};
